### PR TITLE
Examples folder to separate origin from other library experiments

### PR DESCRIPTION
**Pull request by headwinds**
I really liked your write up and wanted to see if I could port the full map version example to React. 

By adding an examples folder, this gives other developers the opportunity to experiment with the library of their choice. 

Currently, in my example folder, I've just started to crudely port the terrain.js to an es6 view controller class which is more universal and could be imported into an Angular or Ember project. In my case, I'm importing it into a React Terrain component.

### CODE REVIEW

**Comment by mewo2** [comment]
This all looks great! However, as far as I'm concerned this is a finished project, so I won't be accepting any pull requests.

**Comment by headwinds** [comment]
Ahhh ok no worries - would you at least consider updating your README file to warn other developers that you won't be accepting contributions. I would encourage you to change your mind though - it's really cool what you've done - I see lots of potential to weave it into other projects and make improvements.

**Comment by ldd** [comment]
@headwinds what is the status of the cleanup to be used with react?

I was thinking that this is really cool, and making a react component out of it would be awesome!
On the other hand, I cannot open an issue here or on your fork, so I feel a [little bit lost](https://xkcd.com/979/)

(sorry if this feels spammy)

**Comment by headwinds** [comment]
@ldd well... you could grab what I started [here](https://github.com/headwinds/terrain)
```
cd examples/react/react-redux
npm install
npm run 
 ```
cool to hear you're interested in react components - not spammy at all! I had started to put together an map exporter to save the map so that you can load and work on the same map again. I've done further work which I've haven't committed yet attempting to turn the map into a little point and click adventure game as a fun side project. If that interests, perhaps we could collaborate...

**Comment by headwinds** [comment]
@ldd I've [enabled issues](https://github.com/headwinds/terrain/issues/1) now on the fork so we could discuss advancing the react work

**Pull request closed without merging**
